language: python
python:
  - "2.6"
  - "2.7"
notifications:
    email: false 
script: nosetests

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda
    # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
    - sudo rm -rf /dev/shm
    - sudo ln -s /run/shm /dev/shm 
install:
    # install gcc-4.8 with c++11 support: https://github.com/travis-ci-tester/travis-test-gcc-cxx-11
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update
    - sudo apt-get install g++-4.8
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90
    - sudo apt-get install liblapack-dev
    - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose dateutil pandas statsmodels
    # Coverage packages are on my binstar channel
    - conda install --yes -c dan_blanchard python-coveralls nose-cov 
    - python setup.py install
