language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
# command to run tests
script: nosetests
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq
install:
# install gcc-4.8 with c++11 support: https://github.com/travis-ci-tester/travis-test-gcc-cxx-11
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update
- sudo apt-get install g++-4.8
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90
- python setup.py install
